name: build mern image and push to docker hub

on:
  push:
   branches:
      - "main"

jobs:
  deploy-S3-bucket:
    name: S-3
    runs-on: ubuntu-latest


    steps:
    - name: AWS Credential
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
        aws-region: us-east-1
    - name: Push to AWS S3 Bucket
      run: aws s3 sync . s3://basit56700
